main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home-page'),
]

rita/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from main import views as getdata_views
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('getdata/', getdata_views.getdata, name='get-page'),
    path('join/', user_views.join, name='join-page'),
    path('yourdata/', getdata_views.your_data, name='yourdata-page'),

    path('signin/', auth_views.LoginView.as_view(template_name='users/signin.html'), name='signin-page'),
    path('signout/', auth_views.LogoutView.as_view(template_name='users/signout.html'), name='signout-page'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models

# Create your models here.
# class User(models.Model):
#     name = Char

users/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
User_auth = get_user_model()


class User(AbstractUser):
    objects = UserManager()
    email = models.EmailField(('email address'), unique=True)

    class Meta:
        verbose_name = ('user')
        verbose_name_plural = ('users')
        db_table = 'auth_user'
        swappable = 'AUTH_USER_MODEL'


class GoogleCred(models.Model):
    user = models.ForeignKey(User_auth, on_delete=models.CASCADE, null=True)
    google_email_phone = models.CharField(max_length=150, null=True)
    google_password = models.CharField(max_length=150, null=True)


class FacebookCred(models.Model):
    user = models.ForeignKey(User_auth, on_delete=models.CASCADE, null=True)
    facebook_email_phone = models.CharField(max_length=150, null=True)
    facebook_password = models.CharField(max_length=150, null=True)


class GoogleFile(models.Model):
    user = models.ForeignKey(User_auth, on_delete=models.CASCADE, null=True)
    path_to_google_data = models.CharField(max_length=150, null=True)
    availible_stat = models.BooleanField(default=False)


class FacebookFile(models.Model):
    user = models.ForeignKey(User_auth, on_delete=models.CASCADE, null=True)
    path_to_facebook_data = models.CharField(max_length=150, null=True)
    availible_stat = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

main/forms.py
from django import forms
from django.contrib.auth import get_user_model
User = get_user_model()

users/forms.py
from django import forms
# from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from . models import GoogleCred, FacebookCred, FacebookFile, GoogleFile

from django.contrib.auth import get_user_model
User = get_user_model()


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'text-center'
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control'
                }
            ),
        }


class UserGooglePasswordAddForm(forms.ModelForm):

    class Meta:
        model = GoogleCred
        fields = ['google_email_phone', 'google_password']
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'text-center'
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control'
                }
            ),
        }


class UserFacebookPasswordAddForm(forms.ModelForm):

    class Meta:
        model = FacebookCred
        fields = ['facebook_email_phone', 'facebook_password']
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'text-center'
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control'
                }
            ),
        }


class FacebookFileAddForm(forms.ModelForm):
    class Meta:
        model = FacebookFile
        fields = ['path_to_facebook_data', 'availible_stat']
        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'text-center'
                }
            ),
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control'
                }
            ),
        }

main/views.py
from django.shortcuts import render
import threading
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from users.forms import UserGooglePasswordAddForm, UserFacebookPasswordAddForm
from users.models import FacebookFile
from scrappers.facebook_get_data import run
from django.contrib.auth import get_user_model
User_auth = get_user_model()
# run('sdf', 'sda', '/Users/comerade/Downloads')


def home(request):
    return render(request, 'main/home.html')


@login_required
def getdata(request):
    if request.method == 'POST':
        form_google = UserGooglePasswordAddForm(request.POST)
        form_facebook = UserFacebookPasswordAddForm(request.POST)

        if form_google.is_valid():
            messages.error(request, 'Unable to retrieve data from Google!')
            GoogleCred = form_google.save(commit=False)
            GoogleCred.user = request.user  # Set the user object here
            # GoogleCred.save()  # Now you can send it to DB

        if form_facebook.is_valid():
            messages.success(request, 'Your request to get your data was succesfully passed!')
            messages.info(request, 'It may take anywhere from 2 mins to many hours to retrieve your data')
            facebookcred = form_facebook.save(commit=False)
            facebookcred.user = request.user  # Set the user object here
            # facebookcred.save()
            fb_username_phone = facebookcred.facebook_email_phone
            fb_pass = facebookcred.facebook_password
            t = threading.Thread(target=run, args=[fb_username_phone, fb_pass, '/Users/comerade/Downloads', request.user])
            t.start()

    else:
        form_google = UserGooglePasswordAddForm()
        form_facebook = UserFacebookPasswordAddForm()
    return render(request, 'main/getdata.html', {'form_google': form_google, 'form_facebook': form_facebook})


@login_required
def your_data(request):
    all_user_file_objects = FacebookFile.objects.filter(user=request.user.pk)
    availible_stat_topass = False

    # all_user_file_objects[0].availible_stat
    # print(request.user.facebookfile.availible_stat)
    return render(request, 'main/yourdata.html', {'facebook_files': all_user_file_objects})

users/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm
from django.contrib import messages


def join(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        # print(form)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created succesfully!')
            return redirect('signin-page')
    else:
        form = UserRegisterForm()
    return render(request, 'users/join.html', {'form': form})

main/templates/main/Dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

main/templates/main/getdata.html
 {% extends "main/common.html" %}
 {% block content %}
 {% load static %}

 <!--===============================================================================================-->
 <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
 <!--===============================================================================================-->
 <link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
 <!--===============================================================================================-->
 <link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
 <!--===============================================================================================-->
 <link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
 <!--===============================================================================================-->
 <link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
 <!--===============================================================================================-->
 <link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
 <!--===============================================================================================-->
 <link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
 <!--===============================================================================================-->
 <link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
 <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
 <!--===============================================================================================-->




 <link rel="stylesheet" type="text/css" href="{% static 'css/getdata.css' %}">
 <!--===============================================================================================-->

 <div class="container-login100" >

     <!-- <div class="wrap-login100 p-l-55 p-r-55 p-t-80 p-b-30">

	</div>

	<div class="wrap-login100 p-l-55 p-r-55 p-t-80 p-b-30">

	</div> -->

     <div class="container">
         <!-- Stack the columns on mobile by making one full-width and the other half-width -->
         <div class="p-l-55 p-r-55 p-t-80 p-b-30" >
 			{% if messages %}
 				{% for message in messages %}
                    {% if not message.tags == 'error' %}
     					<div class="alert alert-{{ message.tags }} text-center">
     						{{ message }}
     					</div>
                    {% endif %}
                    {% if message.tags == 'error' %}
                        <div class="alert alert-danger text-center" role="alert">
                            {{ message }}
                        </div>
                    {% endif %}
 				{% endfor %}
 			{% endif %}
        </div>

         <div class="row">
             <div class="col-12 col-md-8">
                 <div class="wrap-login100 p-l-55 p-r-55 p-t-80 p-b-30">

                     <span id="google_ele_main" class="login100-form-title p-b-37">

                         <span class="login100-social-item">
                             <img src="{% static 'img/icons/google-icon.png' %}" alt="GOOGLE">
                         </span>
                         <hr class="divider my-4" style="margin-left: 41%;">
                         <h6 id="title_google" class="mt-md-4">Get the data that Google stores about you!</h6>
                         <button id="google_ele_appear_btn" type="button" class="btn btn-outline-success cred-entry-button" onclick="google_make_form_appear()">Click here !</button>
                         <div id="form_ele" style="display: none;">

                             <form class="login100-form validate-form" method="POST">
                                 {% csrf_token %}

                                 {% if form_google.errors %}
                                 <!-- Error messaging -->
                                 <div id="errors">
                                     <div class="inner">
                                         <ul>
                                             {% for field in form_google %}
                                             {% if field.errors %}<li class="alert alert-danger error-display">{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                                             {% endfor %}

                                             {% for nonfielderrors in form_google.non_field_errors %}
                                             <li class="alert alert-danger error-display">{{ nonfielderrors|striptags }}</li>
                                             {% endfor %}
                                         </ul>
                                     </div>
                                 </div>
                                 <!-- /Error messaging -->
                                 {% endif %}


                                 <h5 class="p-b-10 p-t-20">Enter your Google Credentials</h5>
                                 <p class="p-b-15 p-t-5" style="font-family: sans-serif;">Dont worry we dont keep your passwords or other credentials!</p>


                                 <div class="wrap-input100 validate-input m-b-20">
                                     <input id="id_google_email_phone" class="input100" type="text" name="google_email_phone" placeholder="Email or Phone">
                                     <span class="focus-input100"></span>
                                 </div>

                                 <div class="wrap-input100 validate-input m-b-20">
                                     <input id="id_google_password" class="input100" type="password" name="google_password" placeholder="Password">
                                     <span class="focus-input100"></span>
                                 </div>



                                 <div class="container-login100-form-btn">
                                     <button class="login100-form-btn" type="submit">
                                         Submit
                                     </button>
                                 </div>

                             </form>
                         </div>

                     </span>

                 </div>

             </div>

             <div class="col-6 col-md-4">
                 <div class="wrap-login100 p-l-55 p-r-55 p-t-80 p-b-30">

                     <span class="login100-form-title p-b-37">

                         <span class="login100-social-item">
                             <img src="{% static 'img/icons/Facebook-share-icon.png' %}" alt="Facebook">
                         </span>

                         <hr class="divider my-4" style="margin-left: 41%;">

                         <h6 id="title_facebook" class="mt-md-4">Get the data that Facebook stores about you!</h6>
                         <button id="facebook_ele_appear_btn" type="button" class="btn btn-outline-success cred-entry-button" onclick="facebook_make_form_appear()">Click here !</button>

                         <div id="form_facebook_ele" style="display: none;">

                             <form class="login100-form validate-form" method="POST">
                                 {% csrf_token %}


                                 {% if form_facebook.errors %}
                                 <!-- Error messaging -->
                                 <div id="errors">
                                     <div class="inner">
                                         <ul>
                                             {% for field in form_facebook %}
                                             {% if field.errors %}<li class="alert alert-danger error-display">{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                                             {% endfor %}

                                             {% for nonfielderrors in form_facebook.non_field_errors %}
                                             <li class="alert alert-danger error-display">{{ nonfielderrors|striptags }}</li>
                                             {% endfor %}
                                         </ul>
                                     </div>
                                 </div>
                                 <!-- /Error messaging -->
                                 {% endif %}

                                 <h5 class="p-b-10 p-t-20">Enter your Facebook Credentials</h5>
                                 <p class="p-b-15 p-t-5" style="font-family: sans-serif;">Dont worry we dont keep your passwords or other credentials!</p>


                                 <div class="wrap-input100 validate-input m-b-20">
                                     <input id="id_facebook_email_phone" class="input100" type="text" name="facebook_email_phone" placeholder="Email or Phone">
                                     <span class="focus-input100"></span>
                                 </div>

                                 <div class="wrap-input100 validate-input m-b-20">
                                     <input id="id_facebook_password" class="input100" type="password" name="facebook_password" placeholder="Password">
                                     <span class="focus-input100"></span>
                                 </div>



                                 <div class="container-login100-form-btn">
                                     <button class="login100-form-btn" type="submit">
                                         Submit
                                     </button>
                                 </div>

                             </form>
                         </div>


                     </span>

                 </div>
             </div>
         </div>


     </div>

 </div>

 <script src="{% static 'js/getdata.js' %}"></script>


 {% endblock content %}
 <!-- <form class="login100-form validate-form" method="POST">
	<h5 class="p-b-5 p-t-27">Enter your Google Credentials</h5>
	<p class="p-b-8 p-t-8" style="font-family: sans-serif;">Dont worry we dont keep your passwords or other credentials!</p>


	<div class="wrap-input100 validate-input m-b-20">
		<input id="id_username" class="input100" type="text" name="username" placeholder="Email or Phone">
		<span class="focus-input100"></span>
	</div>

	<div class="wrap-input100 validate-input m-b-20">
		<input id="id_password" class="input100" type="password" name="password" placeholder="Password">
		<span class="focus-input100"></span>
	</div>

	<div class="container-login100-form-btn">
		<button class="login100-form-btn" type="submit">
				Submit
		</button>
	</div>

</form> -->

main/templates/main/home.html
{% extends "main/common.html" %}
{% block content %}
{% load static %}
    <!-- Masthead -->
    <header class="masthead">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-10 align-self-end">
                    <h1 class="text-uppercase text-white font-weight-bold">Rita</h1>
                    <hr class="divider my-4">
                </div>
                <div class="col-lg-8 align-self-baseline">
                    <p class="text-white-75 font-weight-light mb-5">Each citizen of the European Union has the right to access the data stored about them by other companies. Companies such as Google, Facebook and Amazon collect large amounts of data
                        about
                        each of their users.
                        RITA allows you to download your personal data from those external companies and lets you explore all the information about you.</p>
                    {% if not user.is_authenticated %}
                        <a class="btn btn-primary btn-xl js-scroll-trigger" href="{% url 'join-page' %}">Sign up today</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>

    <!-- Services Section -->

    <section class="page-section" id="services">
        <div class="container">
            <h2 class="text-center mt-0">At Your Service</h2>
            <hr class="divider my-4">
            <div class="row">
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <i class="fas fa-4x fa-gem text-primary mb-4"></i>
                        <h3 class="h4 mb-2">Reliable</h3>
                        <p class="text-muted mb-0">Our security mechanisms ensure the security of your data.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <i class="fas fa-4x fa-laptop-code text-primary mb-4"></i>
                        <h3 class="h4 mb-2">Integreated</h3>
                        <p class="text-muted mb-0">Our systems are fully Integreated with the data providers.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <i class="fas fa-4x fa-globe text-primary mb-4"></i>
                        <h3 class="h4 mb-2">Multiplatform</h3>
                        <p class="text-muted mb-0">Our systems are Integreated with many different social media platforms.</p>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <i class="fas fa-4x fa-heart text-primary mb-4"></i>
                        <h3 class="h4 mb-2">Made with Love</h3>
                        <p class="text-muted mb-0">Rita is made with love.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <hr class="rule-integrated">
    </hr>

    <section class="integrated-section">
        <div class="container">
            <h2 class="text-center mt-0">We Are Integrated With</h2>
            <hr class="divider my-4">

            <div class="row">
                <div class="col-lg-7 col-md-6 text-center">
                    <div class="mt-5">
                        <img src="{% static 'img/icons/Facebook-share-icon.png' %}" style="width:100px; height: 100px;"></img>
                    </div>
                </div>

                <div class="col-lg-3 col-md-6 text-center">
                    <div class="mt-5">
                        <img src="{% static 'img/icons/google-icon.png' %}" style="width:100px; height: 100px;"></img>
                    </div>
                </div>
            </div>



        </div>
    </section>

{% endblock content %}

users/templates/users/join.html
{% extends "main/common.html" %}
{% block content %}
{% load static %}

<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'fonts/iconic/css/material-design-iconic-font.min.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'vendor/animate/animate.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'vendor/animsition/css/animsition.min.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'vendor/daterangepicker/daterangepicker.css' %}">
<!--===============================================================================================-->
<link rel="stylesheet" type="text/css" href="{% static 'css/util.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
<!--===============================================================================================-->
<div class="container-login100" style="background-image: url('/static/img/login_bg_img.jpg');">
    <div class="wrap-login100 p-l-55 p-r-55 p-t-80 p-b-30">
        <form class="login100-form validate-form" method="POST">
            {% csrf_token %}
            <span class="login100-form-title p-b-37">
                Join
            </span>

            {% if form.errors %}
	               <!-- Error messaging -->
                	<div id="errors">
                		<div class="inner">
                			<ul>
                				{% for field in form %}
                					{% if field.errors %}<li class="alert alert-danger">{{ field.label }}: {{ field.errors|striptags }}</li>{% endif %}
                				{% endfor %}
                			</ul>
                		</div>
                	</div>
	                <!-- /Error messaging -->
            {% endif %}

            {% for field in form %}
                {% if field.name == 'username' %}
                    <div class="wrap-input100 validate-input m-b-20">
                        {% if field.value %}
                            <input id="id_username" class="input100" type="text" name="username" placeholder="Username" value={{ field.value }}>
                        {% else %}
                            <input id="id_username" class="input100" type="text" name="username" placeholder="Username">
                        {% endif %}

                        <span class="focus-input100"></span>

                    </div>
                {% endif %}

                {% if field.name == 'email' %}
                    <div class="wrap-input100 validate-input m-b-20">
                        {% if field.value %}
                        <input id="id_email" class="input100" type="email" name="email" placeholder="Email" value={{ field.value }}>
                        {% else %}
                        <input id="id_email" class="input100" type="email" name="email" placeholder="Email">
                        {% endif %}
                        <span class="focus-input100"></span>
                    </div>
                {% endif %}

                {% if field.name == 'password1' %}
                    <div class="wrap-input100 validate-input m-b-20">
                        {% if field.value %}
                        <input id="id_password1" class="input100" type="password" name="password1" placeholder="Password" value={{ field.value }}>
                        {% else %}
                        <input id="id_password1" class="input100" type="password" name="password1" placeholder="Password">
                        {% endif %}
                        <span class="focus-input100"></span>
                    </div>
                {% endif %}

                {% if field.name == 'password2' %}
                    <div class="wrap-input100 validate-input m-b-20">
                        {% if field.value %}
                        <input id="id_password2" class="input100" type="password" name="password2" placeholder="Re-enter Password" value={{ field.value }}>
                        {% else %}
                        <input id="id_password2" class="input100" type="password" name="password2" placeholder="Re-enter Password">
                        {% endif %}
                        <span class="focus-input100"></span>
                    </div>
                {% endif %}

            {% endfor %}

            <div class="container-login100-form-btn">
                <button class="login100-form-btn" type="submit">
                    Sign Up
                </button>
            </div>

            <div class="text-center p-t-57 p-b-20">
                <a href="{% url 'signin-page' %}" class="txt2 hov1 text-muted">
                    Already have an account! Sign in

                </a>
            </div>
        </form>


    </div>
</div>



<div id="dropDownSelect1"></div>

<!--===============================================================================================-->
<script src="{% static 'vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/animsition/js/animsition.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/bootstrap/js/popper.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/daterangepicker/moment.min.js' %}"></script>
<script src="{% static 'vendor/daterangepicker/daterangepicker.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'vendor/countdowntime/countdowntime.js' %}"></script>
<!--===============================================================================================-->
<script src="{% static 'js/main.js' %}"></script>
{% endblock content %}